"""
Infrastructure monitoring models.

Server      — a monitored host (physical, VM, container, cloud instance)
ServerMetric — point-in-time metric snapshot for a server
InfraAlert  — threshold-based alert generated by the monitoring engine
"""

from __future__ import annotations

import uuid
from typing import Optional

from sqlalchemy import Boolean, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base
from app.models.mixins import TimestampMixin, UUIDMixin


class Server(UUIDMixin, TimestampMixin, Base):
    """A monitored server / cloud resource."""

    __tablename__ = "servers"

    # Identity
    name: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    hostname: Mapped[str] = mapped_column(String(255), nullable=False)
    ip_address: Mapped[Optional[str]] = mapped_column(String(45), nullable=True)

    # Classification
    server_type: Mapped[str] = mapped_column(
        String(50), nullable=False, default="linux"
    )  # linux | windows | container | vm
    provider: Mapped[str] = mapped_column(
        String(50), nullable=False, default="on-prem"
    )  # aws | gcp | azure | on-prem
    region: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    environment: Mapped[str] = mapped_column(
        String(50), nullable=False, default="production"
    )  # production | staging | dev

    # Health status (updated by monitoring engine)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="healthy"
    )  # healthy | warning | critical | offline

    # Latest metric snapshot (denormalised for fast reads)
    cpu_percent: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    memory_percent: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    disk_percent: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    network_in_mbps: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    network_out_mbps: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    uptime_seconds: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    load_average_1m: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Ownership (FK-less — user who registered the server)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )

    # Relationships
    metrics: Mapped[list["ServerMetric"]] = relationship(
        "ServerMetric",
        back_populates="server",
        cascade="all, delete-orphan",
        lazy="raise",
    )
    infra_alerts: Mapped[list["InfraAlert"]] = relationship(
        "InfraAlert",
        back_populates="server",
        cascade="all, delete-orphan",
        lazy="raise",
    )


class ServerMetric(UUIDMixin, Base):
    """
    Point-in-time metric snapshot.

    No TimestampMixin — ``recorded_at`` is set by the collector at write time,
    not the DB server_default, so we control its value explicitly.
    """

    __tablename__ = "server_metrics"

    from sqlalchemy import DateTime
    from sqlalchemy.orm import mapped_column as _mc

    server_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("servers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Timestamp of collection (set by metric collector, NOT server_default)
    from datetime import datetime as _dt
    recorded_at: Mapped[_dt] = mapped_column(
        "recorded_at",
        __import__("sqlalchemy").DateTime(timezone=True),
        nullable=False,
        index=True,
    )

    # Resource utilisation
    cpu_percent: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    memory_percent: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    disk_percent: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    network_in_mbps: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    network_out_mbps: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    load_average_1m: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    uptime_seconds: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Relationship
    server: Mapped["Server"] = relationship(
        "Server", back_populates="metrics", lazy="raise"
    )


class InfraAlert(UUIDMixin, TimestampMixin, Base):
    """Threshold-triggered infrastructure alert."""

    __tablename__ = "infra_alerts"

    server_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("servers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Alert details
    alert_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # cpu_high | memory_high | disk_high | offline
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False, default="warning"
    )  # warning | critical
    message: Mapped[str] = mapped_column(Text, nullable=False)
    metric_value: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    threshold: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Lifecycle
    is_resolved: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    resolved_at: Mapped[Optional[__import__("datetime").datetime]] = mapped_column(
        __import__("sqlalchemy").DateTime(timezone=True), nullable=True
    )

    # Ownership
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )

    # Relationship
    server: Mapped["Server"] = relationship(
        "Server", back_populates="infra_alerts", lazy="raise"
    )
