"""
Automated Cloud Security Scanners — Evaluates 9 security domain checks across AWS, GCP, and Azure.
"""

from typing import Any


def run_cloud_security_scanners(provider: str = "AWS") -> list[dict[str, Any]]:
    """Runs automated security scanners across simulated cloud infrastructure."""
    return [
        {
            "scan_name": "Public S3 Storage Bucket Exposure",
            "provider": provider,
            "region": "us-east-1",
            "resource": "s3://cloudpulse-prod-backups-bucket",
            "severity": "Critical",
            "category": "Storage",
            "compliance_framework": "CIS",
            "description": "Storage bucket permissions set to ALL_USERS READ/WRITE without Block Public Access enabled.",
            "recommendation": "Enable AWS S3 Block Public Access and restrict bucket ACLs to authorized IAM roles.",
        },
        {
            "scan_name": "Unrestricted Security Group SSH Ingress",
            "provider": provider,
            "region": "us-east-1",
            "resource": "sg-0a4b2c1d89e (prod-web-ingress)",
            "severity": "Critical",
            "category": "Network",
            "compliance_framework": "PCI DSS",
            "description": "Inbound security group rule allows 0.0.0.0/0 ingress traffic on port 22 (SSH).",
            "recommendation": "Remove 0.0.0.0/0 SSH rule. Restrict ingress to corporate Bastion host IP range or AWS SSM Agent.",
        },
        {
            "scan_name": "Overly Permissive IAM Administrator Policy",
            "provider": provider,
            "region": "global",
            "resource": "iam::role/DevOpsWorkerRole",
            "severity": "High",
            "category": "IAM",
            "compliance_framework": "ISO 27001",
            "description": "Role attaches AdministratorAccess inline policy allowing wildcard action `*:*` across all resources.",
            "recommendation": "Apply Principle of Least Privilege. Replace wildcard policy with scoped service-specific IAM roles.",
        },
        {
            "scan_name": "Unencrypted Production Relational Database",
            "provider": provider,
            "region": "us-west-2",
            "resource": "rds:db-instance/cloudpulse-postgres-main",
            "severity": "High",
            "category": "Database",
            "compliance_framework": "HIPAA",
            "description": "RDS PostgreSQL instance storage is not encrypted at rest using AWS KMS Customer Managed Keys.",
            "recommendation": "Modify DB instance to enable KMS encryption at rest and rotate KMS master key annually.",
        },
        {
            "scan_name": "Root Account Missing Multi-Factor Authentication (MFA)",
            "provider": provider,
            "region": "global",
            "resource": "iam::user/root",
            "severity": "Critical",
            "category": "IAM",
            "compliance_framework": "SOC 2",
            "description": "Cloud account root credentials do not have hardware or virtual MFA device enforced.",
            "recommendation": "Immediately enable Hardware TOTP MFA device on root account and lock away recovery credentials.",
        },
        {
            "scan_name": "Inactive IAM Service Account User",
            "provider": provider,
            "region": "global",
            "resource": "iam::user/legacy-ci-deployer",
            "severity": "Medium",
            "category": "IAM",
            "compliance_framework": "NIST CSF",
            "description": "IAM user access key has not been rotated or authenticated in 120 days.",
            "recommendation": "Disable access keys older than 90 days and delete inactive IAM service account users.",
        },
        {
            "scan_name": "Exposed API Key Secret in Public Repository",
            "provider": provider,
            "region": "us-east-1",
            "resource": "git://github.com/cloudpulse/microservices-app",
            "severity": "Critical",
            "category": "Secrets",
            "compliance_framework": "SOC 2",
            "description": "Plaintext GCP Service Account JSON key committed to application configuration file.",
            "recommendation": "Revoke exposed service account key immediately and migrate secrets to HashiCorp Vault or AWS Secrets Manager.",
        },
        {
            "scan_name": "Plaintext Credentials in Environment Config",
            "provider": provider,
            "region": "us-east-1",
            "resource": "k8s:configmap/api-gateway-env",
            "severity": "High",
            "category": "Secrets",
            "compliance_framework": "GDPR",
            "description": "Kubernetes ConfigMap stores unencrypted database password string in plaintext `DATABASE_URL` key.",
            "recommendation": "Use Kubernetes ExternalSecrets Operator linked to AWS Secrets Manager to inject secrets at runtime.",
        },
        {
            "scan_name": "High-Risk Firewall Rule Allowing Database Port Ingress",
            "provider": provider,
            "region": "us-east-1",
            "resource": "fw-rule/allow-5432-public",
            "severity": "High",
            "category": "Network",
            "compliance_framework": "CIS",
            "description": "VPC firewall rule opens PostgreSQL port 5432 directly to public internet range 0.0.0.0/0.",
            "recommendation": "Restrict PostgreSQL port 5432 ingress solely to private application subnet VPC CIDR blocks.",
        },
    ]
