apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cloudpulse-system
  labels:
    app: cloudpulse-backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: cloudpulse-backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cloudpulse-system
  labels:
    app: cloudpulse-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: cloudpulse-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: cloudpulse-system
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cloudpulse-system
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
