"""
Deterministic Local Fixture Telemetry Provider for Enterprise SLO Center.
Provides internally consistent telemetry data when live production telemetry is absent.
"""

from __future__ import annotations

from typing import Any

FIXTURE_SERVICES_TELEMETRY: list[dict[str, Any]] = [
    {
        "service": "api-gateway",
        "scenario": "Healthy Service",
        "indicator_type": "availability",
        "target_slo": 99.9,
        "total_events": 1250000,
        "good_events": 1249750,
        "bad_events": 250,
        "availability_pct": 99.98,
        "error_rate_pct": 0.02,
        "latency_p50_ms": 14.2,
        "latency_p90_ms": 28.5,
        "latency_p95_ms": 38.0,
        "latency_p99_ms": 72.0,
        "throughput_rps": 450.0,
        "window": "30d",
        "status": "HEALTHY",
    },
    {
        "service": "auth-service",
        "scenario": "Healthy Service",
        "indicator_type": "latency",
        "target_slo": 99.9,
        "total_events": 850000,
        "good_events": 849575,
        "bad_events": 425,
        "availability_pct": 99.95,
        "error_rate_pct": 0.05,
        "latency_p50_ms": 22.0,
        "latency_p90_ms": 48.0,
        "latency_p95_ms": 65.0,
        "latency_p99_ms": 110.0,
        "throughput_rps": 280.0,
        "window": "30d",
        "status": "HEALTHY",
    },
    {
        "service": "payment-service",
        "scenario": "High Latency & SLO Breach",
        "indicator_type": "latency",
        "target_slo": 99.9,
        "total_events": 420000,
        "good_events": 413280,
        "bad_events": 6720,
        "availability_pct": 98.40,
        "error_rate_pct": 1.60,
        "latency_p50_ms": 340.0,
        "latency_p90_ms": 620.0,
        "latency_p95_ms": 780.0,
        "latency_p99_ms": 1450.0,
        "throughput_rps": 120.0,
        "window": "30d",
        "status": "BREACHED",
    },
    {
        "service": "notification-service",
        "scenario": "Burn Rate Incident",
        "indicator_type": "availability",
        "target_slo": 99.9,
        "total_events": 980000,
        "good_events": 971180,
        "bad_events": 8820,
        "availability_pct": 99.10,
        "error_rate_pct": 0.90,
        "latency_p50_ms": 45.0,
        "latency_p90_ms": 95.0,
        "latency_p95_ms": 140.0,
        "latency_p99_ms": 310.0,
        "throughput_rps": 310.0,
        "window": "30d",
        "status": "AT_RISK",
    },
    {
        "service": "analytics-service",
        "scenario": "Error Rate Spike",
        "indicator_type": "error_rate",
        "target_slo": 99.5,
        "total_events": 650000,
        "good_events": 629200,
        "bad_events": 20800,
        "availability_pct": 96.80,
        "error_rate_pct": 3.20,
        "latency_p50_ms": 85.0,
        "latency_p90_ms": 210.0,
        "latency_p95_ms": 340.0,
        "latency_p99_ms": 890.0,
        "throughput_rps": 190.0,
        "window": "30d",
        "status": "BREACHED",
    },
    {
        "service": "frontend",
        "scenario": "Recovered Service",
        "indicator_type": "availability",
        "target_slo": 99.9,
        "total_events": 2100000,
        "good_events": 2098320,
        "bad_events": 1680,
        "availability_pct": 99.92,
        "error_rate_pct": 0.08,
        "latency_p50_ms": 38.0,
        "latency_p90_ms": 85.0,
        "latency_p95_ms": 120.0,
        "latency_p99_ms": 240.0,
        "throughput_rps": 720.0,
        "window": "30d",
        "status": "HEALTHY",
    },
    {
        "service": "worker-service",
        "scenario": "Availability Degradation",
        "indicator_type": "availability",
        "target_slo": 99.5,
        "total_events": 540000,
        "good_events": 534060,
        "bad_events": 5940,
        "availability_pct": 98.90,
        "error_rate_pct": 1.10,
        "latency_p50_ms": 62.0,
        "latency_p90_ms": 140.0,
        "latency_p95_ms": 210.0,
        "latency_p99_ms": 480.0,
        "throughput_rps": 150.0,
        "window": "30d",
        "status": "AT_RISK",
    },
]


def get_fixture_telemetry(service_name: str | None = None) -> list[dict[str, Any]]:
    """Returns deterministic fixture telemetry data."""
    if service_name:
        return [s for s in FIXTURE_SERVICES_TELEMETRY if s["service"] == service_name]
    return FIXTURE_SERVICES_TELEMETRY
